### ISSUE TITLE
make an anticheat

### ISSUE THREAD

**Issue by dries-c** [BlockHorizons/PluginRequests#1]
That can catch:
- killaura
- fly
- speed
- aimaura
- highjump
- forceop

**Comment by TheDiamondYT1** [comment]
I dont get how force op is a thing. It is borderline impossible.

**Comment by dries-c** [comment]
Its posible sac has it and it works

Op 14-jul.-2017 17:20 schreef "Luke | 14" <notifications@github.com>:

**Comment by TheDiamondYT1** [comment]
@Driesboy That is an Anticheat plugin and the code makes no sense to me. Force OP only works if you have the password of a server operator. The way it works on PC is it cycles through a ton of different passwords trying to login as an admin

**Comment by Sandertv** [comment]
Agreed @TheDiamondYT1, I have never understood any way to 'force op' anybody. Operator status is entirely managed server sided, none client sided. It is possible to cycle through the password mentioned by @TheDiamondYT1, but it's up to the authentication plugin to block logging in from the same IP address or client ID if a certain limit has been exceeded within a given amount of time.

**Comment by asyncthreading** [comment]
This plugin its useless, PMMP already got a good anticheat and from 1.1 you're not allowed anymore to run "hacks" on mcpe.

**Comment by asyncthreading** [comment]
@TheDiamondYT1 @Driesboy @Sandertv

**Comment by dries-c** [comment]
I have hacks for mcpe 1.1.3 so
