### ISSUE TITLE
Nemisys on php

### ISSUE THREAD

**Issue by ghost** [BlockHorizons/PluginRequests#11]
Can you create one software proxy , like Nemisys, but in C,C++,C# OR PHP?
I like C#, C++ and C because don't use MORE RAM and RESOURCES.
If you don't know these language of programming, can you create on PHP.

If you create this on C#,C or C++ or PHP  you can create and one PLUGIN in PHP or JAVA or C# (For MiNET), like SynapsePM. 👍

**Comment by TheDiamondYT1** [comment]
We only do plugins, but might do this in the future
