### ISSUE TITLE
Network Managing Commands.

### ISSUE THREAD

**Issue by asyncthreading** [BlockHorizons/PluginRequests#12]
The plugin mechanics are like this:
/gban <name> <time in days> <silent(yes/no)> reason
/gmute <name> <time in minutes> <silent(yes/no)> reason
When someone gets punished by one of those commands and it is not silentban the ban will show in chat to everyone
/gban Doggo 3d no hacker -> This will be a non silent ban!
Most likely to use MYSQL as bans storage.

**Comment by asyncthreading** [comment]
PS: /gban should ban him IP+CID+NAME!

**Comment by TheDiamondYT1** [comment]
Maybe I'll work on a plugin like BanManager for PC and create a website with it too

**Comment by TheDiamondYT1** [comment]
As you can see we already have quite a lot of requests so could take a while
