### ISSUE TITLE
Account Protect

### ISSUE THREAD

**Issue by AffanStarPure** [BlockHorizons/PluginRequests#15]
Hello i want request plugin For Account Protect Not Auth Plugin I need that account protection on player 
I explain it how to be work
for account Protect
- if u try use Steve account won't enabled join on server and kick like Changed You Account Name but not in game like prelogin before join

- How Enabled Join Use Client ID And IP Address only both same 1.23.23.23 will enable join so IP keep changed use client ID Bypass it Name For Blocked It

- so put config only IP : client : Name :  Message  that it not Command

Can You add for PMMP i really like add it please don't closed issue hope you understand.

**Comment by TheDiamondYT1** [comment]
You are required to sign into Xbox Live in the 1.2 update. We should not block the name Steve as only one person in the world will have that gamertag.

**Comment by AffanStarPure** [comment]
Oh thanks you i didn't know thanks @TheDiamondYT1  :)
