### ISSUE TITLE
seat plugin

### ISSUE THREAD

**Issue by SaeedSoheili** [BlockHorizons/PluginRequests#16]
hello
i need seat plugin for GenisysPro 
when i tap the block  53 id i seat on it.

**Comment by Sandertv** [comment]
Since you are using a third-party-modified variation of PocketMine-MP, this issue is considered invalid and will be closed.

**Comment by TheDiamondYT1** [comment]
@Sandertv I think you'll find PMMP/PocketMine-MP is a spoon of PocketMine/PocketMine-MP.

**Comment by Thunder33345** [comment]
I think you will find that PocketMine/PocketMine-MP is unmaintained and as stated on their [readme](https://github.com/PocketMine/PocketMine-MP#weve-moved-head-over-to-here-to-get-some-goodies), they are moved to [PMMP/PocketMine-MP](https://github.com/pmmp/pocketmine-mp)

**Comment by TheDiamondYT1** [comment]
But that is not official. You can say it is, but unless shoghi explicitly states that PMMP/PocketMine-MP is the new home, it remains a spoon.

**Comment by Sandertv** [comment]
Shoghi has stated that he agreed with the move to this new repository. Furthermore, the team primarily consists out of former PocketMine team members, and thus that is the most official it could get.

Also, I have never even said which PocketMine I mean. I was talking about PocketMine-MP in the new repository, and not the dead repository. That should be quite obvious, don't you think?

**Comment by TheDiamondYT1** [comment]
@Sandertv Last comment: where did he say he supports it?
