### ISSUE TITLE
Add Temp DeathBans

### ISSUE THREAD

**Issue by timbersquirrel** [BlockHorizons/PluginRequests#17]
This would be a reall cool plugin

**Comment by Sandertv** [comment]
Please elaborate more, without specifying what exactly this plugin should look like, we cannot create it for you.

**Comment by Kris-Driv** [comment]
Players will be punished with temporary ban for dying. Ban time is calculated based on deaths. I've made similar plugin before.

**Comment by timbersquirrel** [comment]
Well it would be an idea that’s all if you can’t make it oh well

**Comment by timbersquirrel** [comment]
It would be the player from for X amount of time after they die and it could be editable in config
