### ISSUE TITLE
PerWorldInventory request!!

### ISSUE THREAD

**Issue by BrianZP** [BlockHorizons/PluginRequests#2]
## PerWorldInventory:
An inventory plugin to have different inventories on different worlds.
## Features:
The plugin includes the following,
- Supports [PocketMine-MP](https://github.com/pmmp/PocketMine-MP) only,
- Separate inventory on different worlds,
- Ability to have same inventory on certain worlds via mentioning them in config.yml,
- Saves player inventory data in NBTs.
## Port:
There does already exists a [PerWorldInventory](https://github.com/Enrick3344/PerWorldInventory) but its limited on features and plus inventory data saving is not NBT related. Also it does not support enchants but its worth mentioning as its related to the topic and it may be needing a port because its developer seems to have stopped working on it.

Its a request as I am not that much good at php, only a beginner. So help is needed. Thanks. And @Sandertv I love your plugins especially BlockPets.

**Comment by Sandertv** [comment]
Good description and fine plugin, I don't see why not. :) I'll start working on it.

Thanks!

**Comment by Sandertv** [comment]
There you go!
https://poggit.pmmp.io/ci/BlockHorizons/PerWorldInventory/~

If anything doesn't work, (which is quite likely) please post an issue here: https://github.com/BlockHorizons/PerWorldInventory

**Comment by TheDiamondYT1** [comment]
What happened to using `Loader` as the main class name 😂

**Comment by Sandertv** [comment]
Only when all it does is loading things. (Blame me for messing that up in BlockPets) 😂

**Comment by TheDiamondYT1** [comment]
How does it mess up things?

**Comment by Sandertv** [comment]
It doesn't, but names are (sometimes) important for finding out where code is.

**Comment by BrianZP** [comment]
Thanks a ton @Sandertv. This solved my issue and plus many mores to a great extent!!
