### ISSUE TITLE
SlimeFun Port from Spigot to Pocketmine

### ISSUE THREAD

**Issue by McMelonTV** [BlockHorizons/PluginRequests#34]
Hello, it would be awesome if you could port plugin [Slimefun](github.com/TheBusyBiscuit/Slimefun4) from Spigot to Pocketmine

**Comment by McMelonTV** [comment]
r u still alive? @Sandertv @Muqsit @jasonwynn10

**Comment by McMelonTV** [comment]
???
xD

**Comment by Kris-Driv** [comment]
Could you update the link?

**Comment by lukeeey** [comment]
That would be a huge undertaking

**Comment by McMelonTV** [comment]
https://github.com/Slimefun/Slimefun4

**Comment by McMelonTV** [comment]
@Kris-Driv

**Comment by Kris-Driv** [comment]
Seriously? After a whole year? :D

**Comment by McMelonTV** [comment]
Sorry lol i got the notification just yesterday

**Comment by lukeeey** [comment]
> Seriously? After a whole year? :D

I'm commenting on old issues to try and close some

**Comment by Kris-Driv** [comment]
> > Seriously? After a whole year? :D
> 
> I'm commenting on old issues to try and close some

You have my pardon
