### ISSUE TITLE
BackPack Plugin.

### ISSUE THREAD

**Issue by asyncthreading** [BlockHorizons/PluginRequests#4]
All this plugin has to do is when you mine something it will come in your inventory.

**Comment by Sandertv** [comment]
Isn't there such a plugin already?

**Comment by asyncthreading** [comment]
I searched on github and i didnt finded one.

**Comment by Sandertv** [comment]
You could try AutoInv by @JackNoordhuis, that should do the job for you.

**Comment by asyncthreading** [comment]
Thank you :p
