### ISSUE TITLE
Rename Item

### ISSUE THREAD

**Issue by AffanStarPure** [BlockHorizons/PluginRequests#6]
Hmm i try request plugin rename item 
Explain it
- Command /rename {name} for item 
- Can make for PMMP only?
- What about Economy you can add if not pls don't close issue

**Comment by TheDiamondYT1** [comment]
Why does everyone keep asking for PMMP only?

**Comment by Sandertv** [comment]
Because spoons are evil :P

**Comment by TheDiamondYT1** [comment]
But spoons support 32-bit!

**Comment by AffanStarPure** [comment]
Oh I like that it bc anvil won't work on pocket mine so pls add plugin rename so I can rename on game by command only hope u added it :) try u best if u can

**Comment by TheDiamondYT1** [comment]
Here you go! https://github.com/BlockHorizons/ItemRename

You can use the commands `/itemrename`, `/irename` or `/irn` to rename the item currently in your hand. You must be using the latest PMMP build as well. It uses the permission `itemrename.rename`.

In the future i'll add support for renaming items in a specific hotbar slot, and i'll add economy support but right now it is `2:07 am`.

**Comment by TheDiamondYT1** [comment]
@Sandertv Technically it's not done since he asked for Economy support and i havent added it yet. 

We need to finish Switchbox! 😃

**Comment by Sandertv** [comment]
Fiiiiinneeee 😂

**Comment by AffanStarPure** [comment]
Lol thanks you so much make plugin u are best development :)

**Comment by TheDiamondYT1** [comment]
Thanks ;)  We make take a while to finish some plugins since we have lots of projects to work on
