### ISSUE TITLE
Network-Plugin for Nukkit

### ISSUE THREAD

**Issue by Akuroma** [BlockHorizons/PluginRequests#9]
Is it possible to code a plugin, which transfers players between Nukkit-Servers? Similar to BungeeCord for Bukkit? @TheDiamondYT1 I know I'm torturing you with my requests xD But whould this be possible to do for you?
Example: You type in /server 1 or /transfer IP Port and you get ported onto the specified server.
Or if that specified server isn't reachable you get transferred to a specified "fallback" server? :)

**Comment by TheDiamondYT1** [comment]
Too much work. I dont like Nukkit
